# Generated by Django 3.0.7 on 2021-04-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressinfo',
            name='village',
        ),
    ]
