# Generated by Django 3.0.7 on 2021-04-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20210414_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='place_of_birth',
            field=models.DateField(),
        ),
    ]
