# Generated by Django 3.0.7 on 2021-04-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20210414_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=247676, unique=True),
        ),
    ]
